services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: alugo
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app/target # For live reloading
      - ./src:/app/src # For live reloading
      - ./pom.xml:/app/pom.xml # For efficient build
      - mvn-cache:/root/.m2
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432'

volumes:
  mvn-cache: